# NN WITH GATED RECURRENT UNITS
archive:
dataset_name: Traffic
in_size: 24
out_size: 24
batch_size: 16
tcn_epochs: 25
gru_epochs: 25
arima_window: 480
arima_m: 24

test_size: 512

save_results_as: traffic_test.pickle